apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote-api
    name: vote
  name: vote
  namespace: emojivote
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  ports:
  - name: voteapi-service-clusterip
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: vote-api
    version: v1
  sessionAffinity: None
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: emoji-api
    name: emoji
  name: emoji
  namespace: emojivote
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  ports:
  - name: emojiapi-service-clusterip
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: emoji-api
    version: v1
  sessionAffinity: None
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
    name: frontend-emojivote
  name: frontend-emojivote
  namespace: emojivote
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  ports:
  - name: webapp-service-clusterip
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend-emojivote
    version: v1
  sessionAffinity: None
  type: ClusterIP
